### ISSUE TITLE
导入后死机?

### ISSUE THREAD

**Issue by toyjack** [m13253/rime-nihongo-romaji#1]
El Capitan下Squirrel 0.9.26.1

每次重新加载就会不停小彩虹, dict文件删掉大半后可用- -

请问还有在维护么

**Comment by m13253** [comment]
由于rime几个设计上的局限性，我觉得我可能没法实现全部我理想中的功能。
所以我抛弃并且不维护了。
抱歉。

**Comment by toyjack** [comment]
能否问下哪些局限呢?是引擎性能上的问题么?

**Comment by m13253** [comment]
第一个是促音的转换：连续按两下相同的辅音字母，第一个字母转换为 っ。我试了很多方法都没能完美达到我的目的。
第二个是引擎的性能问题：Rime 的引擎在我见过的输入法当中算差的：即使是默认的朙月拼音，和其他拼音输入法相比也更卡，占用更多 CPU。

**Comment by toyjack** [comment]
您回复的好快。性能上的话mozc会有优势吧？请问还有些什么类似的开源引擎呢？

**Comment by tsehygit** [comment]
如果不再維護應該將碼庫封存讓新用者知道。
